# Site settings
title: RiffPointer's Hub # site title
description: >- # site description
  The hub of RiffPointer.
lang: en-US # default lang
timezone: Asia/Kolkata # set your timezone
image: assets/img/ogp.png # This image used for Open Graph more info https://ogp.me/
repo: https://github.com/piharpi/jekyll-klise # site repo [optional]
mode: dark # default theme "dark" | "light"

# Comments
giscus:
  repo: riffpointer/riffpointer.github.io
  repo_id: R_kgDORtuMVg
  category: Giscus Comments
  category_id: DIC_kwDORtuMVs4C9B22
  mapping: og:title
  strict: 0
  reactions_enabled: 1
  emit_metadata: 0
  input_position: bottom
  theme: preferred_color_scheme # follows the visitor's system/theme preference
  lang: en
  loading: lazy

# Profile settings
author:
  name: RiffPointer # author name
  bio: >- # tell to the world
    Casual nerd. I also make videos on YouTube.
  username: riffpointer # general username
  github: riffpointer # github username
  twitter: # twitter username
  facebook: # facebook username
  email: riffpointer@gmail.com # email adress
  avatar: /assets/img/avatar.jpg # change with your own avatar

# URL settings
url: "https://riffpointer.github.io" #
baseurl:
permalink: /:title/
google_analytics: # leave it blank if not wish
fb_appid:

# Collection setting
collections:
  posts:
    output: true

# Markdown settings
markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Default front matter
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: true
  - scope:
      path: ""
      type: pages
    values:
      comments: false

# Jekyll Compose default front matter
jekyll_compose:
  post_default_front_matter:
    modified:
    tags: []
    description:
  draft_default_front_matter:
    modified:
    tags: []
    description:

# Homepage limit posts
number_of_posts: 5
reading_time_words_per_minute: 200

# Build settings
# theme: klise
sass:
  style: compressed
  sourcemap: never

include:
  - _redirects
  - .htaccess

exclude:
  - docs
  - tools
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - CHANGELOG.md
  - README.md
  - THEME.README.md
  - node_modules
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - lighthouse.png
  - klise-*.gem
  - klise.gemspec

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-postfiles
